id: A1D5A9914
title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of the
  Non-Sectarian Teachings of the Buddha'
type: translation
pechas:
- I764D66A6
- IB4DE978B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:39.949154
  last_modified_at: 2023-01-04 11:52:39.949159
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I764D66A6/39BA: 4C9B
  IB4DE978B/A93A: 4C9B
